CREATE DATABASE EVS;
GRANT ALL PRIVILEGES ON EVS.* TO 'EVS'@'%' identified by 'eUGWSAycNg24f5JzGRTN6e8EXoRx7cR3JpJcimQLotGuZzfJA6Lzfkbdx5zToBWZsfqu44PYnAJGjyGCw4Dyd53csdxjMmVBGGYZy3TYwXwMmT4JycijRzfzzj5Vw2nq';
